### ISSUE TITLE
Figure out replacement for Firebase Storage (not available on Node.js)

### ISSUE THREAD

**Issue by bradleypickard** [uclasoles/UCLA-SOLES-website#24]
Looking into 'Google Cloud Storage' may be useful -- https://medium.com/@stardusteric/nodejs-with-firebase-storage-c6ddcf131ceb

**Comment by kyleromero98** [comment]
Lol nice label. Whenever you feel like you need input for something feel free to put something like this issue up and I'll be sure to take a look.

So first let's assume that you have a way of storing the files. From a high-level what would happen is the following:
- The user would hit the submit button (suppose we have fields for test name, prof, class, and the file)
- The file would be uploaded using some function and a URL to the file should be returned
- The Firestore database would then store a reference to this file via the URL along with the metadata information (test name, prof, class, etc.)

I think the way to get around this problem is to have a separate file with plain Javascript which contains some upload function which takes the file and returns its URL (or something like that) and then import that into the file that contains the component you want to use the upload function.

A somewhat useful looking [link](https://www.fullstackfirebase.com/firebase-storage/introd).

[This person](https://stackoverflow.com/questions/51220383/how-do-i-use-firebase-storage-from-a-client-side-react-app) seemed to have luck using it without doing what I suggested above.

A [Youtube video](https://www.youtube.com/watch?v=YR4roPyfDQU) where they appear to be implementing what I'm describing.

I would suggest trying something small from the above as a sanity check/proof of concept to see if it works. Some of these sources are a little old so it's possible that they recently removed support for Javascript/node.js. But, I doubt that because React/node are such popular platforms. 

Finally, if none of this works or if you've already tried the above and it didn't work. Then, put up a pull request for what you've done and we can merge that into the master branch. Then, I can take a look at it and see what might need to be done to the project or whatever.
